main/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('relationfinder.urls')),
]

relationfinder/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.login_or_register, name='login_or_register'),
    path('logout', views.logoutUser, name='logout'),
    path('create', views.create, name='create'),
    path('update_card/<str:pk>', views.update_card, name='update_card'),
    path('delete_card/<str:pk>', views.delete_card, name='delete_card'),
    path('savedata', views.save_form_data, name='savedata'),
    path('similarities', views.similarities, name='similarities'),
    path('mycards', views.mycards, name='mycards'),
    path('messages', views.messages, name='messages'),
    path('user/<str:pk>', views.get_user, name='user'),
    path('viewcard/<str:pk>', views.viewcard, name='viewcard'),
    path('dialogue/<str:pk>', views.dialogue, name='dialogue'),
    path('usersearch', views.usersearch, name='usersearch'),
    path('profile', views.profile, name='profile'),
    path('settings', views.profilesettings, name='profilesettings'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweetme1/urls.py
from django.contrib import admin
from django.urls import path, include

from tweets.views import (home_view, tweet_detail_view,
    tweet_list_view, tweet_create_view
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view),
    path('asd', home_view),
    path('abc/', home_view),
    path('create-tweet', tweet_create_view),
    path('tweets/<int:tweet_id>', tweet_detail_view),
    path('tweets', tweet_list_view),
    path('relf/', include('relationfinder.urls')),
]

relationfinder/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.contrib.auth.models import User

# Create your models here.


def override_username(self):
    name = '{} {} {}'.format(self.userExtension.surname,
                             self.userExtension.first_name, self.userExtension.fathername)
    return name


User.add_to_class("__str__", override_username)


class Card(models.Model):
    class Meta:
        verbose_name_plural = "Cards"
        verbose_name = "Card"

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="card_set", blank=True, null=True)
    card_name = models.CharField(
        max_length=30, blank=False, null=False, default="default name")

    sex = models.CharField(max_length=30, blank=False,
                           null=False, default="default")
    relation_level = models.CharField(
        max_length=30, blank=False, null=False, default="default")

    first_name = models.CharField(max_length=30, blank=True, null=True)
    surname = models.CharField(max_length=30, blank=True, null=True)
    fathername = models.CharField(max_length=30, blank=True, null=True)

    birth_year = models.PositiveIntegerField(blank=True, null=True)
    death_year = models.PositiveIntegerField(blank=True, null=True)

    place1_x = models.FloatField(blank=True, null=True)
    place1_y = models.FloatField(blank=True, null=True)
    place1_radius = models.FloatField(blank=True, null=True)
    place1_start_year = models.PositiveIntegerField(blank=True, null=True)
    place1_end_year = models.PositiveIntegerField(blank=True, null=True)

    place2_x = models.FloatField(blank=True, null=True)
    place2_y = models.FloatField(blank=True, null=True)
    place2_radius = models.FloatField(blank=True, null=True)
    place2_start_year = models.PositiveIntegerField(blank=True, null=True)
    place2_end_year = models.PositiveIntegerField(blank=True, null=True)

    place3_x = models.FloatField(blank=True, null=True)
    place3_y = models.FloatField(blank=True, null=True)
    place3_radius = models.FloatField(blank=True, null=True)
    place3_start_year = models.PositiveIntegerField(blank=True, null=True)
    place3_end_year = models.PositiveIntegerField(blank=True, null=True)

    information = models.TextField(null=True, blank=True)

    def __str__(self):
        return '{} {} {} ({} для {}) '.format(self.surname, self.first_name, self.fathername, self.relation_level, str(self.user))

    def save(self, *args, **kwargs):
        if self.first_name:
            self.first_name = self.first_name.capitalize()
        if self.surname:
            self.surname = self.surname.capitalize()
        if self.fathername:
            self.fathername = self.fathername.capitalize()
        return super(Card, self).save(*args, **kwargs)


class UserExtension(models.Model):
    user = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.CASCADE, related_name='userExtension')
    first_name = models.CharField(max_length=30, blank=True, null=True)
    surname = models.CharField(max_length=30, blank=True, null=True)
    fathername = models.CharField(max_length=30, blank=True, null=True)
    birth_date = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    information = models.TextField(blank=True, null=True)
    photo = models.ImageField(blank=True, null=True,
                              default="def_profile_photo.png")

    def __str__(self):
        return '{} {} {}'.format(self.surname, self.first_name, self.fathername)


class Message(models.Model):
    written_to = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True, related_name="wtMessages_set")
    written_by = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True, related_name="wbMessages_set")
    text = models.TextField(blank=True, null=True)
    datetime = models.DateTimeField(auto_now_add=True, blank=True, null=False)


class Relation(models.Model):
    referenced_by = models.ForeignKey(
        Card, on_delete=models.CASCADE, blank=True, null=True, related_name="fbRelations_set")
    referencing = models.ForeignKey(
        Card, on_delete=models.CASCADE, blank=True, null=True, related_name="rtRelations_set")
    connection_type = models.CharField(max_length=30, blank=True, null=True)
    similarity = models.FloatField(null=True, blank=True)

relationfinder/forms.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Card, UserExtension, Message


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class DateInput(forms.DateInput):
    input_type = 'date'


class UserExtensionEditForm(forms.ModelForm):
    class Meta:
        model = UserExtension
        fields = [
            'first_name',
            'surname',
            'fathername',
            'birth_date',
            'information',
            'photo',
        ]
        widgets = {
            'birth_date': DateInput(format='%Y-%m-%d')
        }


class UserExtensionRegForm(forms.ModelForm):
    class Meta:
        model = UserExtension
        fields = [
            'first_name',
            'surname',
            'fathername',
            'birth_date',
        ]


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = '__all__'
        exclude = ['user', 'card_name']

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['written_to', 'text']

relationfinder/views.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Q
from .filters import UserExtFilter
from .algorithm import evaluate
from .forms import CardForm, RegisterForm, UserExtensionRegForm, UserExtensionEditForm, MessageForm
from .models import Card, UserExtension, Relation
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages as msgs


@login_required(login_url='login_or_register')
def profile(request):
    return render(request, "relfinder/profile_main.html")


@login_required(login_url='login_or_register')
def profilesettings(request):
    userEx = request.user.userExtension
    form = UserExtensionEditForm(instance=userEx)
    if request.method == 'POST':
        form = UserExtensionEditForm(
            request.POST, request.FILES, instance=userEx)
        if form.is_valid():
            form.save()
            return redirect('profile')
        else:
            return HttpResponse("Форма заполнена неверно")
    return render(request, "relfinder/profile_settings.html", {'form': form})


@login_required(login_url='login_or_register')
def similarities(request):
    all_relations = Relation.objects.all()
    user_relations = all_relations.filter(referenced_by__user=request.user)

    return render(request, "relfinder/profile_similarities.html", {'user_relations': user_relations})


@login_required(login_url='login_or_register')
def mycards(request):
    return render(request, "relfinder/profile_mycards.html")


@login_required(login_url='login_or_register')
def logoutUser(request):
    logout(request)
    return redirect('login_or_register')


def login_or_register(request):
    if request.user.is_authenticated:
        return redirect('profile')
    else:
        if request.method == "POST":
            reqType = request.POST.get('type')
            if reqType == 'login':
                username = request.POST.get('username')
                password = request.POST.get('password')
                user = authenticate(
                    request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('profile')
                else:
                    return HttpResponse("the user doesn't exist")

            elif reqType == 'register':
                userRegForm = RegisterForm(request.POST)
                userExRegForm = UserExtensionRegForm(request.POST)
                if userRegForm.is_valid() and userExRegForm.is_valid():
                    user = userRegForm.save()
                    userEx = userExRegForm.save(commit=False)
                    userEx.user = user
                    userEx.save()
                    msgs.success(request, "Регистрация прошла успешно! Выполните вход.")
                    return render(request, 'relfinder/login_or_register.html')
                else:
                    return HttpResponse("Form is invalid")
            elif reqType == 'ajax':
                username = request.POST['username']
                if User.objects.filter(username=username).count():
                    return HttpResponse("этот логин уже занят")
                else:
                    return HttpResponse("")
                

            else:
                return HttpResponse("an error occurred")

        else:
            return render(request, 'relfinder/login_or_register.html')


@login_required(login_url='login_or_register')
def create(request):
    return render(request, "relfinder/profile_createcard.html")


@login_required(login_url='login_or_register')
def save_form_data(request, *args, **kwargs):
    form = CardForm(request.POST or None)
    if form.is_valid():                 
        obj = form.save(commit=False)   
        obj.user = request.user
        obj.save()
        evaluate(obj)
    else:
        return HttpResponse("Форма заполнена некорректно")
    return redirect("profile")


@login_required(login_url='login_or_register')
def get_user(request, pk):
    if request.user.id == int(pk):
        return redirect('profile')
    try:
        user = User.objects.get(id=pk)
    except ObjectDoesNotExist:
        return HttpResponse("Пользователь не существует")

    return render(request, "relfinder/profile_viewuser.html", {'user': user})


@login_required(login_url='login_or_register')
def viewcard(request, pk):
    try:
        card = Card.objects.get(id=pk)
    except ObjectDoesNotExist:
        return HttpResponse("Карточка не существует")
    showButtons = False
    if card.user == request.user:
        showButtons = True
    return render(request, "relfinder/profile_viewcard.html", {'card': card, 'showButtons': showButtons})


@login_required(login_url='login_or_register')
def update_card(request, pk):
    card = Card.objects.get(id=pk)
    if card.user == request.user:
        if request.method == 'POST':
            form = CardForm(request.POST, instance=card)
            if form.is_valid():
                Q_obj = Q(referenced_by=card) | Q(referencing=card)
                Relation.objects.filter(Q_obj).delete()
                newCard = form.save()
                evaluate(newCard)
                return redirect('viewcard', newCard.id)
            else:
                return HttpResponse("Форма заполнена некорректно")
        elif request.method == 'GET':
            return render(request, "relfinder/profile_updatecard.html", {'card':card})
        else:
            return HttpResponse("Неизвестный метод отправки формы")
    else:
        return HttpResponse("Вы не можете изменять карточки других пользователей")


@login_required(login_url='login_or_register')
def delete_card(request, pk):
    card = Card.objects.get(id=pk)
    if card.user == request.user:
        card.delete()
    else:
        return HttpResponse("Вы не можете удалять карточки других пользователей")
    return redirect('mycards')


@login_required(login_url='login_or_register')
def usersearch(request):
    userExtensions = UserExtension.objects.all().exclude(
        id=request.user.userExtension.id)

    userFilter = UserExtFilter(request.GET, userExtensions)
    userExtensions = userFilter.qs

    context = {
        'userExtensions': userExtensions,
        'userFilter': userFilter,
    }
    return render(request, "relfinder/profile_usersearch.html", context)


@login_required(login_url='login_or_register')
def messages(request):
    if request.method == "POST":
        form = MessageForm(request.POST)
        obj = form.save(commit=False)   # returns object instance
        obj.written_by = request.user
        obj.save()
        return redirect(request.POST['redirect'])
    elif request.method == "GET":
        wbmessages = request.user.wbMessages_set
        wt_users = wbmessages.values_list('written_to', flat=True).distinct()
        wtmessages = request.user.wtMessages_set
        wb_users = wtmessages.values_list('written_by', flat=True).distinct()
        ids = set(list(wt_users) + list(wb_users))
        users = User.objects.filter(id__in=ids)
        return render(request, "relfinder/profile_messages.html", {'users': users})


@login_required(login_url='login_or_register')
def dialogue(request, pk):
    messagesToPkUser = request.user.wbMessages_set.filter(written_to=pk)
    messagesByPkUser = request.user.wtMessages_set.filter(written_by=pk)
    messages = messagesToPkUser | messagesByPkUser
    messages = messages.order_by('datetime')
    return render(request, "relfinder/profile_dialogue.html", {'messages': messages, 'userPk': pk})

relationfinder/templates/relfinder/login_or_register.html
{% extends 'relfinder/base.html' %}

{% block headtitle %}
Вход/Регистрация
{% endblock headtitle %}

{% block content%}



<div class="container my-4">


    {% if messages %}
    <div id="msg">
        {% for message in messages %}
        <div class="alert alert-success ">
            <div class="text-center">
                <h5>{{message}}</h5>
            </div>
        </div>
        {% endfor %}
    </div>

    <script>
        setTimeout(function () {
            $('#msg').remove();
        }, 2000)
    </script>

    {% endif %}



    <div class="row">
        <div class="col-1"></div>
        <div class="col-10 p-0">
            <div class="row">

            </div>
        </div>
        <div class="col-1"></div>

        <div class="col-5 p-0">
            <div class="bg-light p-3 shadow" style="border-radius: 12px; position: relative;
            transform: translate(0%,70%);">
                <h4 class="text-center">Вход</h4>
                <form method="POST" autocomplete="off" action="{% url 'login_or_register' %}">
                    {% csrf_token %}
                    <input type="hidden" name="type" value="login" />
                    <div class="form-group">
                        <label>Логин</label>
                        <div>
                            <input type="text" class="form-control" name="username" maxlength="150" required=""
                                id="id_username">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Пароль</label>
                        <div>
                            <input type="password" class="form-control opacity-3" name="password" required=""
                                id="id_password">
                        </div>
                    </div>
                    <div class="row">
                        <button type="submit" class="mx-auto btn border border-dark">Вход</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-2 p-0 m-0"></div>

        <div class="col-5 p-0">
            <div class="bg-light p-3 shadow" style="border-radius: 12px;">
                <h4 class="text-center">Регистрация</h4>
                <form method="POST" autocomplete="off" action="{% url 'login_or_register' %}">
                    {% csrf_token %}
                    <input type="hidden" name="type" value="register" />
                    <div class="form-group">
                        <label>Логин</label>
                        <div>
                            <input type="text" id="login" class="form-control" name="username" maxlength="150"
                                required="" id="id_username">
                            <div class="p-1 text-danger" id="login_response" >
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Имя</label>
                        <div>
                            <input type="text" class="form-control" name="first_name" maxlength="30" required=""
                                id="id_first_name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Фамилия</label>
                        <div>
                            <input type="text" class="form-control" name="surname" maxlength="150" required=""
                                id="id_surname">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Отчество</label>
                        <div>
                            <input type="text" class="form-control" name="fathername" maxlength="150" required=""
                                id="id_fathername">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Дата рождения</label>
                        <div>
                            <input type="date" class="form-control" name="birth_date" maxlength="150" required=""
                                id="id_birth_date">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Пароль</label>
                        <div>
                            <input type="password" class="form-control" name="password1" required="" id="id_password1">
                            <ul class="p-0 pl-4 pt-2">
                                <li>пароль не может быть похож на остальную информацию.</li>
                                <li>пароль не должен содержать менее 8 символов.</li>
                                <li>пароль не должен быть часто используемым.</li>
                                <li>пароль не может полностью состоять из цифр.</li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Подтвержение пароля</label>
                        <div>
                            <input type="password" class="form-control" name="password2" required="" id="id_password2">
                        </div>
                    </div>
                    <div class="row">
                        <button type="submit" class="mx-auto btn border border-dark">Регистрация</button>
                    </div>

                </form>
            </div>

        </div>

    </div>



</div>

{% endblock content %}

{% block script %}
<script>
    $(document).ready(function () {

        $("#login").keyup(function () {

            var username = $(this).val().trim();

            if (username != '') {

                $.ajax({
                    url: '/',
                    type: 'post',
                    data: {
                        type: 'ajax',
                        username: username,
                        csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value
                    },
                    success: function (response) {

                        $('#login_response').html(response);
                    }
                });
            } else {
                $("#login_response").html("");
            }
        });
    });
</script>
{% endblock script %}

relationfinder/templates/relfinder/profile_dialogue.html
{% extends 'relfinder/profile_navigation.html' %}

{% block headtitle %}
Диалог
{% endblock headtitle %}

{% block content1 %}


<div class="container bg-light shadow-sm rounded p-2">

    <div class="container   p-0 mb-2">
        <h6 class="text-center">Диалог с пользователем</h6> 
    </div>

    <div class="m-0 border pt-2 pb-2" id="scroll_1" style="height: 500px; overflow-y:scroll; ">

        {% for message in messages %}

        <div class="row m-0 mb-4">
            <div class="col-2 m-0 p-0" style="max-width: 11%;">
                <div class="m-0 p-0">
                    <div class="m-0 p-0 float-right"
                        style="background-image:url('{{ message.written_by.userExtension.photo.url }}'); 
                background-repeat:no-repeat; 
                background-size:cover; background-position: center; height: 70px; width: 70px; border-radius: 50%; border-style: solid; border-color: rgb(210, 210, 210); border-width: 1px;">
                    </div>
                </div>
            </div>
            <div class="col-10">
                <div class="p-0 m-0">
                    <a href="{% url 'user' message.written_by.id %}" style="font-weight:normal;">{{message.written_by}}</a>
                    <div style="font-size: small;">
                        {{message.datetime}}
                    </div>
                    <div class="pt-1">
                        {{message.text}}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <hr class="mt-0 mb-0">

    <div class="p-2">
        <form action="{% url 'messages' %}" method="POST" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}
            <p>
                <label  class="pl-2" for="id_information">Введите сообщение:</label>
                <textarea name="text" class="form-control form-control-sm" cols="40"
                    rows="7"></textarea>
            </p>
            <input type="hidden" name="written_to" value="{{ userPk }}">
            <input type="hidden" name="redirect" value="/dialogue/{{ userPk }}">
            <div class="row">
                <input type="submit" class="btn mx-auto border btn-primary" name="update" value="Отправить">
            </div>
        </form>
    </div>


</div>

<script>
var element = document.getElementById("scroll_1");
element.scrollTop = element.scrollHeight;
</script>






{% endblock content1 %}

relationfinder/templates/relfinder/profile_settings.html
{% extends 'relfinder/profile_navigation.html' %}

{% block headtitle %}
Настройки профиля
{% endblock headtitle %}

{% block content1 %}


<!-- <div class="container bg-light rounded border shadow p-3">
    <form action="" method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        {{form.as_p}}

        <input type="submit" class="btn border" name="update" id=""></input>
    </form>
</div> -->

<div class="col-9 m-0 p-0">
    <div class="m-2 p-0">
        <div class="container bg-light rounded shadow p-3">
            <form action="" method="POST" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}

                <p>
                    <label for="id_first_name">Имя:</label>
                    <input type="text" class="form-control form-control-sm" name="first_name"
                        value="{{form.first_name.value}}" maxlength="30" id="id_first_name">
                </p>
                <p>
                    <label for="id_surname">Фамилия:</label>
                    <input type="text" class="form-control form-control-sm" name="surname"
                        value="{{form.surname.value}}" maxlength="30" id="id_surname">
                </p>
                <p>
                    <label for="id_fathername">Отчество:</label>
                    <input type="text" class="form-control form-control-sm" name="fathername"
                        value="{{form.fathername.value}}" maxlength="30" id="id_fathername">
                </p>
                <p>
                    <label for="id_birth_date">Дата рождения:</label>
                    <input type="date" class="form-control form-control-sm" name="birth_date"
                        value="{{form.birth_date.value|date:'Y-m-d'}}" id="id_birth_date">
                </p>
                <p>
                    <label for="id_information">Дополнительная информация:</label>
                    <textarea name="information" class="form-control form-control-sm" cols="40" rows="7"
                        id="id_information">{{form.information.value}}</textarea>
                </p>

                <p>
                    <label for="id_photo">Текущее фото:</label>
                    <a href="{{request.user.userExtension.photo.url}}">{{request.user.userExtension.photo}}</a><br>
                    Изменить:
                    <input type="file" name="photo" class="" accept="image/*" id="id_photo">

                </p>
                <div class="row">

                    <input type="submit" class="btn mx-auto border btn-primary" name="update" id="" value="Применить">
                </div>
                
            </form>
        </div>
    </div>
</div>

{% endblock content1 %}

relationfinder/templates/relfinder/profile_usersearch.html
{% extends 'relfinder/profile_navigation.html' %}

{% block content1 %}

<div class="row mb-3">
    <div class="col">
        <div class="bg-light rounded shadow-sm px-2 py-2">
            <form action="" method="get" autocomplete="off" class="form-inline">
                <label for="id_surname" class="mr-sm-2">Фамилия:</label>
                <input type="text" class="form-control form-control-sm mr-sm-3" name="surname" value=""
                    id="id_first_name">
                <label for="id_first_name" class="mr-sm-2">Имя:</label>
                <input type="text" class="form-control form-control-sm mr-sm-3" name="first_name" value=""
                    id="id_surname">
                <label for="id_fathername" class="mr-sm-2">Отчество:</label>
                <input type="text" class="form-control form-control-sm" name="fathername" value=""
                    id="id_fathername">
                <button class=" btn btn-sm btn-primary mx-auto" type="submit">Поиск</button>
            </form>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-11">
        {% for userExtension in userExtensions %}
        <div class="container rounded shadow mb-2 mt-0 mr-0 ml-0 p-0 bg-light">
            <div class="row">
                <div class="col-3">

                    <div class="ml-2 my-2 mr-0 p-0">
                        <img src="{{ userExtension.photo.url }}" class="img-thumbnail">
                    </div>
                </div>
                <div class="col-9 pt-2 pl-0">
                    <a style="font-size: 12.5pt;" href="{% url 'user' userExtension.user.id %}">{{userExtension.user}}</a>
                    <hr class="my-1 mr-5 p-0">
                    <div class="text-muted" style="font-size: 10.5pt;">
                        Дата рождения: {{ userExtension.birth_date }}
                    </div>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-1">
    </div>
</div>




{% endblock content1 %}

relationfinder/templates/relfinder/profile_viewuser.html
{% extends 'relfinder/profile_navigation.html' %}

{% block headtitle %}
{{ user.userExtension.first_name }} {{ user.userExtension.fathername }}
{{ user.userExtension.surname }}
{% endblock headtitle %}

{% block content1 %}
<div class="row ">
    <div class="col-4">
        <div class=" ml-1 my-1 mr-0 p-1 bg-light shadow rounded">
            <img src="{{ user.userExtension.photo.url }}" class="mb-0 border img-thumbnail rounded    ">
            <div class="p-1 px-2">
                <button class="btn btn-primary btn-sm btn-block" data-toggle="modal" data-target="#myModal"
                type="button">Отправить сообщение</button>
            </div>
            
        </div>
    </div>

    <div class="modal" id="myModal">
        <div class="container shadow border bg-light pb-4 pl-4 pr-4 mt-4 rounded-lg" id="popup"
            style="max-width: 800px; position: relative; transform: translate(0%,30%);">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <form action="{% url 'messages' %}" method="POST" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                <p>
                    <label for="id_information">Введите сообщение:</label>
                    <textarea name="text" class="form-control form-control-sm" cols="40"
                        rows="15"></textarea>
                </p>
                <input type="hidden" name="written_to" value="{{user.id}}">
                <input type="hidden" name="redirect" value="/user/{{ user.id }}">
                <div class="row">
                    <input type="submit" class="btn mx-auto border btn-primary" name="update" value="Отправить">
                </div>
            </form>
        </div>
    </div>


    <div class="col-8 m-0 p-0">
        <div class="m-0 mt-1 p-3 shadow border bg-light rounded ">
            <b>{{ user.userExtension.first_name }} {{ user.userExtension.fathername }}
                {{ user.userExtension.surname }}</b>
            <hr class="my-2 mr-5 p-0">
            Дата рождения: {{ user.userExtension.birth_date }}
            <hr class="mt-2 mb-3 mr-5 p-0">
            <div class="mr-5 mb-3">
                {% if user.userExtension.information %}
                {{ user.userExtension.information }}
                {% else %}
                <p class="text-muted">Информация не задана.</p>
                {% endif %}
            </div>


        </div>
    </div>
</div>
{% endblock content1 %}